Repository testla-project/testla-screenplay-playwright-js, pull requests merged in 2023-12, with the labels that each got.

#48 21 better structure of readme
  .gitignore
  .vscode/settings.json
  CODE_OF_CONDUCT.md
  README.md
  docs/guides/advanced_test_setup/create_action.md
  docs/guides/advanced_test_setup/create_question.md
  docs/guides/advanced_test_setup/create_task.md
  docs/guides/advanced_test_setup/write_tests.md
  docs/guides/assets/screenplay_pattern.png
  docs/guides/basic_test_setup/actor_fixture.md
  docs/guides/basic_test_setup/screen.md
  docs/guides/basic_test_setup/writing_tests.md
  docs/guides/guides.md
  docs/screenplay_elements/API/Ability/use_api.md
  docs/screenplay_elements/API/Actions/delete.md
  docs/screenplay_elements/API/Actions/get.md
  docs/screenplay_elements/API/Actions/head.md
  docs/screenplay_elements/API/Actions/patch.md
  docs/screenplay_elements/API/Actions/post.md
  docs/screenplay_elements/API/Actions/put.md
  docs/screenplay_elements/API/Miscellaneous/a_request.md
  docs/screenplay_elements/API/Questions/response.md
  docs/screenplay_elements/Shared/Actions/sleep.md
  docs/screenplay_elements/Web/Ability/browse_the_web.md
  docs/screenplay_elements/Web/Actions/add.md
  docs/screenplay_elements/Web/Actions/check.md
  docs/screenplay_elements/Web/Actions/clear.md
  docs/screenplay_elements/Web/Actions/click.md
  docs/screenplay_elements/Web/Actions/double_click.md
  docs/screenplay_elements/Web/Actions/drag_and_drop.md
  docs/screenplay_elements/Web/Actions/fill.md
  docs/screenplay_elements/Web/Actions/get.md
  docs/screenplay_elements/Web/Actions/hover.md
  docs/screenplay_elements/Web/Actions/navigate.md
  docs/screenplay_elements/Web/Actions/press.md
  docs/screenplay_elements/Web/Actions/remove.md
  docs/screenplay_elements/Web/Actions/select.md
  docs/screenplay_elements/Web/Actions/set.md
  docs/screenplay_elements/Web/Actions/type.md
  docs/screenplay_elements/Web/Actions/wait.md
  docs/screenplay_elements/Web/Miscellaneous/utils.md
  docs/screenplay_elements/Web/Questions/element.md
  docs/screenplay_elements/screenplay_elements.md
  docs/screenplay_pattern_overview/screenplay_pattern.md
  src/api/abilities/UseAPI.ts
  src/web/abilities/BrowseTheWeb.ts
  src/web/utils.ts
Labels: documentation

#54 49 setup pipeline to test our stuff
  __tests__/web.spec.ts
  __tests__/web_playwright_locators.spec.ts
Labels: bug

#55 46 replace type function and add presssequentially support
  __tests__/web.spec.ts
  __tests__/web_playwright_locators.spec.ts
  docs/screenplay_elements/Web/Ability/browse_the_web.md
  docs/screenplay_elements/Web/Actions/press.md
  package-lock.json
  package.json
  src/web/abilities/BrowseTheWeb.ts
  src/web/actions/Press.ts
  src/web/actions/Type.ts
Labels: enhancement, wip
