Repository testla-project/testla-screenplay-playwright-js, pull requests merged in 2024-01, with the labels that each got.

#67 Allow lazy loading of locators in web actions
  __tests__/web_playwright_locators.spec.ts
  src/web/types.ts
  src/web/utils.ts
Labels: enhancement

#70 Change docu to avoid license violation
  docs/guides/assets/screenplay.png
  docs/screenplay_pattern_overview/screenplay_pattern.md
Labels: documentation

#72 Documenting lazy selectors
  __tests__/web_playwright_locators.spec.ts
  docs/guides/assets/screenplay_pattern.png
  docs/guides/basic_test_setup/screen.md
Labels: documentation

#74 fixed issue with input type lazy selector for getElement
  __tests__/web.spec.ts
  src/web/abilities/BrowseTheWeb.ts
Labels: bug
